package com.gc.controller;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletResponse;


@Controller
public class SlackController {
    /**RequestMapping for slackmessagesuccess called by submitslackmessage form
     * @param cookieToken returned by temp page
     * @param message message text passed in by form
     * @param privateChannel usesrname for message to go to passed in by form
     * @param response saves userid and channel to cookies
     * @return page veryifying message was sent
     */
    @RequestMapping(value = "/slackmessagesuccess", method = RequestMethod.GET)
    public String privatemessage(@CookieValue("cookieToken") String cookieToken, @RequestParam("slackmessage") String message, @RequestParam("channel") String privateChannel, HttpServletResponse response) {

        String userId = OAuthMethods.getUserID(cookieToken);
        privateChannel = OAuthMethods.getChannelId2(cookieToken, privateChannel);
        response.addCookie(new Cookie("cookieChannelId", privateChannel));
        response.addCookie(new Cookie("cookieUserId", userId));
        OAuthMethods.sendPrivateMessage(cookieToken, message, privateChannel, userId);
        return "slackmsgsuccess";
    }


    /**RequestMapping for method called by slack login page after a successful userlogin.
     * Calls OAuthMethods controller to get unique token code and creates a cookie with that value to store.
     * @param model accesstoken added to template
     * @param code tempCode generated by temp page as part of OAuth authorization tempcode generated inside of getOAuthToken
     * @param response Adds a cookie with OAuthToken as a cookie value
     * @return returns to home page if successful
     */
    @RequestMapping(value = "/loginSlack", method = RequestMethod.GET)
    //the String method returns the jsp page that we want to show
    //also redirects to the home page after login in with slack
    public String loginSlack(Model model, @RequestParam("tempCode") String code, HttpServletResponse response) {

        String accessToken = OAuthMethods.getOAuthToken(code);
        response.addCookie(new Cookie("cookieToken", accessToken));
        model.addAttribute("token", accessToken);

        return "home";
    }
}
